---
- name: view configuration of both remote server nginx file
  hosts: all
  become: true
  tasks:
   - name: Get nginx content
     shell: cat /etc/nginx/nginx.conf
     register: data
     args:
       warn: false

   - debug:
       msg: "{{ data.stdout_lines }}"
