---
- name: view configuration of both remote server nginx file
  hosts: ll
  become: true
  tasks:
   - name: Get nginx content
     shell: cat /etc/nginx/nginx.conf
     register: data

   - debug:
       msg: "{{ data.stdout }}"
